import {
  FiShield,
  FiStar,
  FiPhone,
  FiTruck,
  FiAlertCircle,
  FiInfo,
} from "react-icons/fi";

export const vehicle = {
  model: "Mahindra & Mahindra",
  fuelType: "Diesel",
  variant: "AT-2157CC",
  policyType: "Bundled (1yr + 3yr OD)",
  regDate: "22-01-23",
  startDate: "22-02-23",
};

export const plans = [
  {
    id: 1,
    insurer: "ICICI Lombard",
    type: "General Insurance",
    logo: "🛡️",
    color: "#E84142",
    accentLight: "#FFF0F0",
    idv: "₹5,24,663",
    badge: "Recommended",
    premium: {
      own: "₹15,780",
      third: "₹10,640",
      addon: "₹0",
      discount: "₹0",
      gst: "₹4,000",
      gross: "₹31,176",
    },
    usps: [
      "Reliable Customer Support",
      "Instant Motor Claims",
      "9700 Cashless Garages",
      "24/7 Customer Support",
    ],
    addons: {
      personalAccident: false,
      engineProtect: true,
      zeroDep: true,
      roadside: true,
      consumables: false,
      returnToInvoice: true,
    },
  },
  {
    id: 2,
    insurer: "Bajaj Allianz",
    type: "General Insurance",
    logo: "🏆",
    color: "#0057A8",
    accentLight: "#EFF5FF",
    idv: "₹5,10,000",
    badge: "Best Value",
    premium: {
      own: "₹20,782",
      third: "₹10,790",
      addon: "₹0",
      discount: "₹9,352",
      gst: "₹4,756",
      gross: "₹31,176",
    },
    usps: [
      "Dual Coverage of Third Party Risks",
      "7100+ Cashless Garages",
      "24/7 Customer Support",
      "Quick Claim Settlement",
    ],
    addons: {
      personalAccident: false,
      engineProtect: false,
      zeroDep: true,
      roadside: true,
      consumables: true,
      returnToInvoice: false,
    },
  },
  {
    id: 3,
    insurer: "HDFC ERGO",
    type: "General Insurance",
    logo: "💎",
    color: "#00845A",
    accentLight: "#EDFAF4",
    idv: "₹5,35,000",
    badge: "Premium",
    premium: {
      own: "₹18,250",
      third: "₹10,640",
      addon: "₹1,200",
      discount: "₹0",
      gst: "₹4,327",
      gross: "₹34,417",
    },
    usps: [
      "10,000+ Cashless Garages",
      "AI-Powered Claims",
      "3-Year Long Term OD",
      "Dedicated Claim Manager",
    ],
    addons: {
      personalAccident: true,
      engineProtect: true,
      zeroDep: true,
      roadside: true,
      consumables: true,
      returnToInvoice: true,
    },
  },
  {
    id: 4,
    insurer: "New India Assurance",
    type: "General Insurance",
    logo: "🇮🇳",
    color: "#F58020",
    accentLight: "#FFF7EE",
    idv: "₹4,98,000",
    badge: null,
    premium: {
      own: "₹14,500",
      third: "₹10,640",
      addon: "₹0",
      discount: "₹0",
      gst: "₹3,622",
      gross: "₹28,762",
    },
    usps: [
      "Government Backed",
      "Pan-India Network",
      "5000+ Cashless Garages",
      "Hassle-Free Claims",
    ],
    addons: {
      personalAccident: false,
      engineProtect: false,
      zeroDep: false,
      roadside: false,
      consumables: false,
      returnToInvoice: false,
    },
  },
];

export const rows = [
  {
    section: "Premium Breakup",
    key: "own",
    label: "Own Damage Premium",
    icon: <FiShield size={14} />,
    bold: false,
    isAddon: false,
  },
  {
    section: "Premium Breakup",
    key: "third",
    label: "Third Party Premium",
    icon: <FiAlertCircle size={14} />,
    bold: false,
    isAddon: false,
  },
  {
    section: "Premium Breakup",
    key: "addon",
    label: "Addon Premium",
    icon: <FiStar size={14} />,
    bold: false,
    isAddon: false,
  },
  {
    section: "Premium Breakup",
    key: "discount",
    label: "Total Discount (NCB 0% Incl.)",
    icon: <FiInfo size={14} />,
    bold: false,
    isAddon: false,
  },
  {
    section: "Premium Breakup",
    key: "gst",
    label: "GST",
    icon: <FiInfo size={14} />,
    bold: false,
    isAddon: false,
  },
  {
    section: "Premium Breakup",
    key: "gross",
    label: "Gross Premium (incl GST)",
    icon: null,
    bold: true,
    isAddon: false,
  },
  {
    section: "Addon Details",
    key: "personalAccident",
    label: "Compulsory Personal Accident",
    icon: <FiShield size={14} />,
    bold: false,
    isAddon: true,
  },
  {
    section: "Addon Details",
    key: "engineProtect",
    label: "Engine Protection",
    icon: <FiTruck size={14} />,
    bold: false,
    isAddon: true,
  },
  {
    section: "Addon Details",
    key: "zeroDep",
    label: "Zero Depreciation",
    icon: <FiStar size={14} />,
    bold: false,
    isAddon: true,
  },
  {
    section: "Addon Details",
    key: "roadside",
    label: "Roadside Assistance",
    icon: <FiPhone size={14} />,
    bold: false,
    isAddon: true,
  },
  {
    section: "Addon Details",
    key: "consumables",
    label: "Consumables Cover",
    icon: <FiInfo size={14} />,
    bold: false,
    isAddon: true,
  },
  {
    section: "Addon Details",
    key: "returnToInvoice",
    label: "Return to Invoice",
    icon: <FiAlertCircle size={14} />,
    bold: false,
    isAddon: true,
  },
];
